name: bioinf_proj
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - r-base=4.3
  - r-seurat
  - r-tidyverse
  - r-ggplot2
  - r-patchwork
  - r-cowplot
  - r-dplyr
  - r-magrittr
  - r-matrix
  - r-knitr
  - r-hdf5r
  - r-remotes
  - pip
  - pip:
      - scrublet
      - scvi-tools
      - scanpy
      - anndata
      - matplotlib
      - seaborn
      - pandas
      - numpy
      - scipy

